### ISSUE TITLE
Need more examples, especially triggering Homekit automation

### ISSUE THREAD

**Issue by mshulman** [ebaauw/homebridge-rpi#6] opened 2020-01-06 16:44 UTC
Thank you for this plugin. It looks like it'll be perfect.

I have everything running, but I'm not sure how to use RPI GPIO pins to start automations. I get this back from the `rpi`command line tool:
pi@raspberrypi:~ $ /opt/nodejs/bin/rpi info
{
  "model": "Zero W",
  "revision": "1.1",
  "processor": "BCM2835",
  "memory": "512MB",
  "manufacturer": "Sony UK",
  "gpioMask": "0xffffffc",
  "serial": "00000000938C8AAC",
  "date": "2020-01-06T16:40:20+00:00",
  "load": 0.61,
  "temp": 30.4,
  "freq": 1000000000,
  "volt": 1.35,
  "throttled": "0x0"
}

Is there a way to break out the GPIO pins? Can I break apart the Mask in Homebridge? Or do we need a new communication channel to alert Homebridge when a GPIO pin changes state?

thanks

**Comment by ebaauw** [comment] 2020-01-06 17:29
Homebridge-rpi already opens a second channel to the `pigpio` server, to receive real-time notifications for changed GPIO pins.
https://github.com/ebaauw/homebridge-rpi/blob/e0eceee102d1a248156228d80ea497ec828f0ba3/lib/PigpioClient.js#L480
Currently, it only subscribes to GPIO 18, which is exposed to HomeKit as a (stateful) _Switch_ service.
https://github.com/ebaauw/homebridge-rpi/blob/e0eceee102d1a248156228d80ea497ec828f0ba3/lib/RpiPlatform.js#L102

The mask that `rpi info` reports is for the user-controllable GPIO pins per Raspberry Pi model, not for the subscriptions.

I still need to design a way to specify which GPIO pins you want to expose, and how.  Currently, only _Switch_ and _Lightbulb_ are implemented (for the Pimoroni Fan Shim, exposed when the pi’s name is `pi5`).
https://github.com/ebaauw/homebridge-rpi/blob/e0eceee102d1a248156228d80ea497ec828f0ba3/lib/RpiAccessory.js#L30 
For push buttons, a _Stateless Programmable Switch_ would be more appropriate.

I’m still in doubt whether to expose each GPIO pin as a separate accessory (with its own history), or as a separate service to a single accessory (without history).  I currently settled on the second, also to play around with a combined temperature/power history (not used by any of the Eve devices).  I also haven’t decided yet where to keep the GPIO pin specification: in config.json for all Pi-s or in a separate json file on each Pi.  Would love to hear your thoughts on these decisions.

**Comment by mshulman** [comment] 2020-01-06 17:48
Let me describe my use case:
I have a magnetic window sensor attached to two pins, with an inline resistor. When the window is open, I want to turn off the air conditioner/heater by switching my Nest into Eco mode. When the window is closed, I want to re-enable the previously selected mode.

I am currently doing this with a custom built python script that polls the state of the GPIO pins every 60 seconds, and if the window is open, it sends a command to the Nest service switching to Eco mode. It's pretty hacky - the polling interval is too long, it doesn't read the state of the Nest before forcing it to Eco mode, and worst of all, it requires hardcoded credentials.

I'm now running Homebridge on in a container on my Synology service, and I have the Homebridge-Nest plugin integrated.

Ideally, I'd run wires to multiple windows, either in series, or by connecting to multiple pins on the rpi.

So, what happens today when GPIO 18 goes from close to open, or open to close? Is this an event I can subscribe to in Homekit automation?

**Comment by ebaauw** [comment] 2020-01-06 18:18
> So, what happens today when GPIO 18 goes from close to open, or open to close? Is this an event I can subscribe to in Homekit automation?

The _On_ characteristic changes value accordingly.  You can use this in HomeKit automations.

> I have a magnetic window sensor attached to two pins, with an inline resistor. When the window is open

How do you detect that?  I’d expect that you’d need only one GPIO pin with the other wire to 3.3V or ground.  I suppose this pin would be best exposed to HomeKit as a _Door/Window_ sensor.  
Note that the GPIO numbers differ from the physical pins, see https://pinout.xyz/.

> Ideally, I'd run wires to multiple windows, either in series

Than it would be a single sensor, indicating that any of the windows is open.

> or by connecting to multiple pins on the rpi.

For a sensor per window.

**Comment by dcaccount** [comment] 2020-01-06 21:35
Hello,
First of all congratulations for your great work!
I would love to see each GPIO pin as a separate accessory. I have a Raspberry with a relays hat with also input channels. 
The relays open/close gates and doors and the input channels monitor their status. 
At the moment have been using 

> homebridge-GPIO-device 
that however relies on wiringPi that has been deprecated.

This is the reason why it would be great if I could control and monitor each GPIO pin as separate accessory.

Please advise if I could be of help.
Thanks.
Dan

**Comment by ebaauw** [comment] 2020-01-06 21:59
> I have a Raspberry with a relays hat with also input channels.

Which one?

> The relays open/close gates and doors and the input channels monitor their status.

“Opens” as in: moves, or as in: locks?  How is the status different from the relay status?  Is the input binary?  Digital?  Analogue?

Wouldn’t you rather have an accessory per GPIO pair (of output GPIO driving the relay and input GPIO reporting the state)?

**Comment by mshulman** [comment] 2020-01-07 04:00
@ebaauw : 

Currently, I'm using only magnetic sensor, and it is indeed on GPIO / BCOM 18.  And it is wired to +3.3V to BC 18, in parallel with a resistor (IIRC). 

From Python, 
`GPIO.setmode(GPIO.BCM)`
`GPIO.setup(18, GPIO.IN, pull_up_down=GPIO.PUD_UP)`

I guess, instead of bugging you, I should just try it and see what happens. 

If I get it working, I'll send a PR for updating the docs, if that's ok

**Comment by dcaccount** [comment] 2020-01-07 05:29
> > I have a Raspberry with a relays hat with also input channels.
> 
> Which one?
> Automation Hat
> > The relays open/close gates and doors and the input channels monitor their status.
> 
> “Opens” as in: moves, or as in: locks? How is the status different from the relay status? Is the input binary? Digital? Analogue?
> For instance, when I say 

> open garage door
the relay closes for one second (I decide how long) and triggers the garage opening/closing.

> Wouldn’t you rather have an accessory per GPIO pair (of output GPIO driving the relay and input GPIO reporting the state)?
If would not say so as a every input channel and every relay correspond to a GPIO pi; if you want later today I will drop you my config.json file

Thanks!

**Comment by ebaauw** [comment] 2020-01-07 06:56
> I should just try it and see what happens. 

That won’t work; homebridge-p1 currently uses GPIO 18 as output (the fan shim has fan control wired to this pin).  I’ll see if I can add support for input GPIOs.

**Comment by mshulman** [comment] 2020-01-07 11:23
Are there any pins that are monitored for input? I can easily move the jumper to a different pin

**Comment by mshulman** [comment] 2020-01-07 17:38
Eric,

I get this error repeatedly
`raspberrypi: error: expected FO (104), got SHELL (110)`

then finally:
`warning: raspberrypi: FO (104): error no handle available (-24)`

What should I do to debug?

[homebridge-2.log](https://github.com/ebaauw/homebridge-rpi/files/4031720/homebridge-2.log)

**Comment by mshulman** [comment] 2020-01-07 17:46
This looks suspicious:
`
[1/7/2020, 12:41:46 PM] [Rpi] warning: mshulman: connect ECONNREFUSED 192.168.85.15:8888
[1/7/2020, 12:41:46 PM] [Rpi] warning: raspberrypi: FO (104): error no handle available (-24)
[1/7/2020, 12:41:46 PM] [Rpi] error: raspberrypi: Error: FO (104): error no handle available (-24)
    at PigpioClient._onCmdData (/homebridge/node_modules/homebridge-rpi/lib/PigpioClient.js:396:18)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)

[1/7/2020, 12:41:46 PM] [Rpi] raspberrypi: Raspberry Pi Zero W v1.1 (BCM2835, 512MB) - 
(node:896) UnhandledPromiseRejectionWarning: RangeError: params.id: invalid id
    at new AccessoryDelegate (/homebridge/node_modules/homebridge-rpi/node_modules/homebridge-lib/lib/AccessoryDelegate.js:47:13)
    at new RpiAccessory (/homebridge/node_modules/homebridge-rpi/lib/RpiAccessory.js:14:5)
    at RpiPlatform.checkDevice (/homebridge/node_modules/homebridge-rpi/lib/RpiPlatform.js:111:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1/7/2020, 12:41:47 PM] [Rpi] raspberrypi: remove stale RpiAccessory v0.0.2 accessory 00000000938C8AAC
`

**Comment by mshulman** [comment] 2020-01-07 18:00
I verified that `pigpiod` is set up for remote access:
`root@raspberrypi:~# cat /etc/systemd/system/pigpiod.service.d/public.conf`
`[Service]`
`ExecStart=`
`ExecStart=/usr/bin/pigpiod`

without the `-l` option

**Comment by mshulman** [comment] 2020-01-07 18:08
and this:
`root@raspberrypi:~# cat /opt/pigpio/access`
`/proc/cpuinfo r`
`/opt/pigpio/vcgencmd.out r`

**Comment by mshulman** [comment] 2020-01-07 18:18
I shutdown the other application that was reading the GPIO pins, and I still see this in the log.

My pi is at 192.168.85.41:
`pi@raspberrypi:~ $ hostname -I`
`192.168.85.41 `
`pi@raspberrypi:~ $ ifconfig | grep 192.168`
`        inet 192.168.85.41  netmask 255.255.255.0  broadcast 192.168.85.255`


[1/7/2020, 12:57:58 PM] Loaded plugin: homebridge-rpi
[1/7/2020, 12:57:58 PM] Registering platform 'homebridge-lib.Lib'
[1/7/2020, 12:57:58 PM] Registering platform 'homebridge-rpi.Rpi'
[1/7/2020, 12:57:58 PM] ---
[1/7/2020, 12:57:58 PM] Loaded plugin: homebridge-tplink-smarthome
[1/7/2020, 12:57:58 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[1/7/2020, 12:57:58 PM] ---
[1/7/2020, 12:57:58 PM] Loaded plugin: homebridge-config-ui-x
[1/7/2020, 12:57:58 PM] Registering platform 'homebridge-config-ui-x.config'
[1/7/2020, 12:57:58 PM] ---
[1/7/2020, 12:57:58 PM] Loading 2 platforms...
[1/7/2020, 12:57:58 PM] [Nest] Initializing Nest platform...
[1/7/2020, 12:57:58 PM] [Nest] Fetching Nest devices.
[1/7/2020, 12:57:58 PM] [Rpi] Initializing Rpi platform...
[1/7/2020, 12:57:58 PM] [Rpi] homebridge-rpi v0.0.2, node 12.14.0, homebridge v0.4.50, homebridge-lib v4.4.10
[1/7/2020, 12:57:58 PM] Loading 0 accessories...
Load homebridge-tplink-smarthome.TplinkSmarthome
[1/7/2020, 12:57:58 PM] [homebridge-tplink-smarthome.TplinkSmarthome] homebridge-tplink-smarthome v4.0.1, node v12.14.0, homebridge v0.4.50
[1/7/2020, 12:57:58 PM] [homebridge-tplink-smarthome.TplinkSmarthome] Configuring cached accessory: [Master bedroom] 800612A3541192D36210043AE6065E4E19CF5935 625aa623-692d-4076-8ddc-ecc7212ffdd9
[1/7/2020, 12:57:59 PM] [Rpi] warning: mshulman: connect ECONNREFUSED 192.168.85.15:8888
[1/7/2020, 12:57:59 PM] [Rpi] warning: raspberrypi: connect ECONNREFUSED 192.168.85.41:8888
[1/7/2020, 12:58:00 PM] [Nest] initing thermostat "Entryway": deviceId: 09AA01AC16160QLH structureId: f0f8f151-4974-11e7-8d7e-0e29ed7818e8
[1/7/2020, 12:58:00 PM] [Nest] initing home_away_sensor "Home/Away": deviceId: f0f8f151-4974-11e7-8d7e-0e29ed7818e8 structureId: f0f8f151-4974-11e7-8d7e-0e29ed7818e8
[1/7/2020, 12:58:00 PM] [Nest] initing temp_sensor "Living Room": deviceId: 18B430C5E1E80640 structureId: f0f8f151-4974-11e7-8d7e-0e29ed7818e8
[1/7/2020, 12:58:00 PM] [Nest] Initializing platform accessory 'Entryway'...
[1/7/2020, 12:58:00 PM] [Nest] Initializing platform accessory 'Home/Away'...
[1/7/2020, 12:58:00 PM] [Nest] Initializing platform accessory 'Living Room'...
Setup Payload:
<snip...>
[1/7/2020, 12:58:00 PM] Homebridge is running on port 52509.
[1/7/2020, 12:58:19 PM] [homebridge-tplink-smarthome.TplinkSmarthome] New Device Online: [Master bedroom] plug [800612A3541192D36210043AE6065E4E19CF5935] 192.168.85.92 9999
[1/7/2020, 12:58:19 PM] [homebridge-tplink-smarthome.TplinkSmarthome] Adding: [Master bedroom] plug [800612A3541192D36210043AE6065E4E19CF5935]
[1/7/2020, 1:12:54 PM] [Rpi] warning: mshulman: connect ECONNREFUSED 192.168.85.15:8888

**Comment by ebaauw** [comment] 2020-01-07 19:10
> [1/7/2020, 1:12:54 PM] [Rpi] warning: mshulman: connect ECONNREFUSED 192.168.85.15:8888

Are you sure `pigpiod` is running?  Is the other application also a `pigpio` application?  Only one of them can be active at any given time.  When another `pigpio` application is active, homebridge-rpi would connect to that instead of to `pigpiod`.

> raspberrypi: error: expected FO (104), got SHELL (110)

Homebridge-rpi is expecting a response for the file open command, but receives one for the shell command.  Kinda odd, it sends the shell command first, and only sends the file open command, after the shell command response has been received.  I need to test if it could be interference by another pigpio application.

> warning: raspberrypi: FO (104): error no handle available (-24)

All the file handles at the `pigpio` service are used.  Probably due to homebridge-rpi, not yet doing robust error handling, failing to issue a file close after the file open.  Restart `pigpiod` or the other `pigpio` application, or run `rpi -H 192.168.85.15 closeHandles`.

**Comment by mshulman** [comment] 2020-01-07 19:33
The weird thing is that the machine called `mshulman` isn’t a pi - it’s my Mac laptop. I wonder if there’s a way to specify (in the config file?) which machines it should try to connect to.

I’ll also see if the daemon is running



-ms


On Jan 7, 2020, at 2:10 PM, Erik Baauw <notifications@github.com> wrote:

﻿

[1/7/2020, 1:12:54 PM] [Rpi] warning: mshulman: connect ECONNREFUSED 192.168.85.15:8888

Are you sure pigpiod is running? Is the other application also a pigpio application? Only one of them can be active at any given time. When another pigpio application is active, homebridge-rpi would connect to that instead of to pigpiod.

raspberrypi: error: expected FO (104), got SHELL (110)

Homebridge-rpi is expecting a response for the file open command, but receives one for the shell command. Kinda odd, it sends the shell command first, and only sends the file open command, after the shell command response has been received. I need to test if it could be interference by another pigpio application.

warning: raspberrypi: FO (104): error no handle available (-24)

All the file handles at the pigpio service are used. Probably due to homebridge-rpi, not yet doing robust error handling, failing to issue a file close after the file open. Restart pigpiod or the other pigpio application, or run rpi -H 192.168.85.15 closeHandles.

**Comment by ebaauw** [comment] 2020-01-07 19:46
> The weird thing is that the machine called `mshulman` isn’t a pi - it’s my Mac laptop. I wonder if there’s a way to specify (in the config file?) which machines it should try to connect to.

Of course.  Currently, homebridge-rpi checks each RFB server that announces itself over Bonjour.  This is the protocol used by MacOS screen sharing and VNC.

Specifying the remote Pi-s to connect to is still on the todo list.

**Comment by ebaauw** [comment] 2020-01-07 22:13
> raspberrypi: error: expected FO (104), got SHELL (110)

I've been able to reproduce this.  Somehow, homebridge-lib issues two heartbeats per second (instead of one), causing homebridge-rpi to send two SHELL commands in close succession.  The response of the second SHELL command comes in just after the FO command has been sent.

I'll come up with a fix this weekend.  Until then, as a workaround, you can specify homebridge-lib as a platform in config.json.  No need to install it separately; homebridge-rpi has already registered it.

**Comment by mshulman** [comment] 2020-01-08 03:01
`pigpiod` is *not* running. I'm not sure what I need to do to fix it. 

`● pigpiod.service - Daemon required to control GPIO pins via pigpio
   Loaded: loaded (/lib/systemd/system/pigpiod.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/pigpiod.service.d
           └─public.conf
   Active: failed (Result: exit-code) since Tue 2020-01-07 12:53:53 EST; 9h ago
 Main PID: 3350 (code=exited, status=1/FAILURE)

Jan 07 12:53:52 raspberrypi systemd[1]: Stopped Daemon required to control GPIO pins via pigpio.
Jan 07 12:53:52 raspberrypi systemd[1]: pigpiod.service: Unit entered failed state.
Jan 07 12:53:52 raspberrypi systemd[1]: pigpiod.service: Failed with result 'exit-code'.
Jan 07 12:53:52 raspberrypi systemd[1]: Starting Daemon required to control GPIO pins via pigpio
Jan 07 12:53:53 raspberrypi systemd[1]: Started Daemon required to control GPIO pins via pigpio.
Jan 07 12:53:53 raspberrypi pigpiod[3349]: 2020-01-07 12:53:53 initInitialise: bind to port 8888
Jan 07 12:53:53 raspberrypi pigpiod[3349]: Can't initialise pigpio library
Jan 07 12:53:53 raspberrypi systemd[1]: pigpiod.service: Main process exited, code=exited, statu
Jan 07 12:53:53 raspberrypi systemd[1]: pigpiod.service: Unit entered failed state.
Jan 07 12:53:53 raspberrypi systemd[1]: pigpiod.service: Failed with result 'exit-code'.
`

**Comment by mshulman** [comment] 2020-01-08 03:09
ok, I just did a apt-get update, install, cleaned up some things, and now pigpiod seems to be running.

root@raspberrypi:/home/pi# systemctl status pigpiod
● pigpiod.service - Daemon required to control GPIO pins via pigpio
   Loaded: loaded (/lib/systemd/system/pigpiod.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/pigpiod.service.d
           └─public.conf
   Active: active (running) since Tue 2020-01-07 22:06:25 EST; 5s ago
  Process: 7075 ExecStop=/bin/systemctl kill pigpiod (code=killed, signal=TERM)
  Process: 7133 ExecStart=/usr/bin/pigpiod (code=exited, status=0/SUCCESS)
 Main PID: 7134 (pigpiod)
   CGroup: /system.slice/pigpiod.service
           └─7134 /usr/bin/pigpiod

Jan 07 22:06:25 raspberrypi systemd[1]: Starting Daemon required to control GPIO pins via pigpio...
Jan 07 22:06:25 raspberrypi systemd[1]: Started Daemon required to control GPIO pins via pigpio.

and now it seems to be working:

/homebridge/node_modules/.bin # ./rpi -H 192.168.85.41:8888 info                                                
{                                                                                                               
  "model": "Zero W",                                                                                            
  "revision": "1.1",                                                                                            
  "processor": "BCM2835",                                                                                       
  "memory": "512MB",                                                                                            
  "manufacturer": "Sony UK",                                                                                    
  "gpioMask": "0xffffffc",                                                                                      
  "serial": "00000000938C8AAC",                                                                                 
  "date": "2020-01-08T03:08:05+00:00",                                                                          
  "load": 0.16,                                                                                                 
  "temp": 26.1,                                                                                                 
  "freq": 999998000,                                                                                            
  "volt": 1.35,                                                                                                 
  "throttled": "0x0"                                                                                            
}                                                                                                               
/homebridge/node_modules/.bin # 

I'll add homebridge-lib as a separate platform as well.

**Comment by mshulman** [comment] 2020-01-08 03:15
and... now I see this:

My config.json:
{
    "bridge": {
        "name": "Homebridge D28C",
        "username": "0E:C1:12:18:D2:8C",
        "port": 52509,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "Rpi"
        },
        {
            "platform": "homebridge-lib"
        }
    ]
}


and this in the log, there's a restart loop:

[1/7/2020, 10:13:35 PM] [Rpi] homebridge-rpi v0.0.2, node 12.14.0, homebridge v0.4.50, homebridge-lib v4.4.10
[1/7/2020, 10:13:35 PM] Error: The requested platform 'homebridge-lib' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
[1/7/2020, 10:13:35 PM] Got SIGTERM, shutting down Homebridge...

**Comment by ebaauw** [comment] 2020-01-08 05:51
Sorry, it’s `"platform": "Lib"`, the name under which the platform is registered.

**Comment by mshulman** [comment] 2020-01-08 15:26
ok, we're getting close. After a few restarts and configs, I'm now getting this when I close and open the window. Note the bouncing from true -> false -> true when I open the window

// CLOSE THE WINDOW

[1/8/2020, 10:22:35 AM] [Rpi] raspberrypi GPIO18: set On to false
[1/8/2020, 10:22:35 AM] [Rpi] raspberrypi History: set History Status from "AAAAAAAAAAAFK8YjAgECDgEDAMAPAAAAAAAAAAABAQ==" to "NgAAAAAAAAAFK8YjAgECDgEEAMAPAAAAAAAAAAABAQ=="
[1/8/2020, 10:22:36 AM] [Rpi] raspberrypi: set Load from 0.52 to 0.47
[1/8/2020, 10:22:51 AM] [Rpi] raspberrypi: set Current Temperature from 20.7°C to 21.8°C
[1/8/2020, 10:22:51 AM] [Rpi] raspberrypi: set Load from 0.47 to 0.64

// OPEN THE WINDOW

[1/8/2020, 10:23:00 AM] [Rpi] raspberrypi GPIO18: set On from false to true
[1/8/2020, 10:23:00 AM] [Rpi] raspberrypi History: set History Status from "NgAAAAAAAAAFK8YjAgECDgEEAMAPAAAAAAAAAAABAQ==" to "TwAAAAAAAAAFK8YjAgECDgEFAMAPAAAAAAAAAAABAQ=="
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi GPIO18: set On from true to false
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi History: set History Status from "TwAAAAAAAAAFK8YjAgECDgEFAMAPAAAAAAAAAAABAQ==" to "UAAAAAAAAAAFK8YjAgECDgEGAMAPAAAAAAAAAAABAQ=="
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi GPIO18: set On from false to true
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi History: set History Status from "UAAAAAAAAAAFK8YjAgECDgEGAMAPAAAAAAAAAAABAQ==" to "UAAAAAAAAAAFK8YjAgECDgEHAMAPAAAAAAAAAAABAQ=="
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi GPIO18: set On from true to false
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi History: set History Status from "UAAAAAAAAAAFK8YjAgECDgEHAMAPAAAAAAAAAAABAQ==" to "UAAAAAAAAAAFK8YjAgECDgEIAMAPAAAAAAAAAAABAQ=="
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi GPIO18: set On from false to true
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi History: set History Status from "UAAAAAAAAAAFK8YjAgECDgEIAMAPAAAAAAAAAAABAQ==" to "UAAAAAAAAAAFK8YjAgECDgEJAMAPAAAAAAAAAAABAQ=="
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi GPIO18: set On from true to false
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi History: set History Status from "UAAAAAAAAAAFK8YjAgECDgEJAMAPAAAAAAAAAAABAQ==" to "UAAAAAAAAAAFK8YjAgECDgEKAMAPAAAAAAAAAAABAQ=="
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi GPIO18: set On from false to true
[1/8/2020, 10:23:01 AM] [Rpi] raspberrypi History: set History Status from "UAAAAAAAAAAFK8YjAgECDgEKAMAPAAAAAAAAAAABAQ==" to "UAAAAAAAAAAFK8YjAgECDgELAMAPAAAAAAAAAAABAQ=="

**Comment by ebaauw** [comment] 2020-01-08 17:33
> Note the bouncing from true -> false -> true when I open the window

We need to check if that still occurs when the GPIO is configured for input mode and, with a pull up register.  Could you run (on the Pi):
```
$ pigs modes 18 r
$ pigs pud 18 u
```

**Comment by mshulman** [comment] 2020-01-08 19:20
I ran those two commands. They returned without messages or errors.

Afterwards, when I opened the window, I saw this in the logs:

[1/8/2020, 2:16:36 PM] [Rpi] raspberrypi: set Load from 0.15 to 0.26
**[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi GPIO18: set On from false to true**
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi History: set History Status from "6DUAAAAAAAAFK8YjAgECDgEvAMAPAAAAAAAAAAABAQ==" to "ETcAAAAAAAAFK8YjAgECDgEwAMAPAAAAAAAAAAABAQ=="
**[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi GPIO18: set On from true to false**
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi History: set History Status from "ETcAAAAAAAAFK8YjAgECDgEwAMAPAAAAAAAAAAABAQ==" to "ETcAAAAAAAAFK8YjAgECDgExAMAPAAAAAAAAAAABAQ=="
**[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi GPIO18: set On from false to true**
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi History: set History Status from "ETcAAAAAAAAFK8YjAgECDgExAMAPAAAAAAAAAAABAQ==" to "ETcAAAAAAAAFK8YjAgECDgEyAMAPAAAAAAAAAAABAQ=="
**[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi GPIO18: set On from true to false**
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi History: set History Status from "ETcAAAAAAAAFK8YjAgECDgEyAMAPAAAAAAAAAAABAQ==" to "ETcAAAAAAAAFK8YjAgECDgEzAMAPAAAAAAAAAAABAQ=="
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi GPIO18: set On from false to true
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi History: set History Status from "ETcAAAAAAAAFK8YjAgECDgEzAMAPAAAAAAAAAAABAQ==" to "ETcAAAAAAAAFK8YjAgECDgE0AMAPAAAAAAAAAAABAQ=="
**[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi GPIO18: set On from true to false**
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi History: set History Status from "ETcAAAAAAAAFK8YjAgECDgE0AMAPAAAAAAAAAAABAQ==" to "ETcAAAAAAAAFK8YjAgECDgE1AMAPAAAAAAAAAAABAQ=="
**[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi GPIO18: set On from false to true**
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi History: set History Status from "ETcAAAAAAAAFK8YjAgECDgE1AMAPAAAAAAAAAAABAQ==" to "ETcAAAAAAAAFK8YjAgECDgE2AMAPAAAAAAAAAAABAQ=="
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi GPIO18: set On from true to false
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi History: set History Status from "ETcAAAAAAAAFK8YjAgECDgE2AMAPAAAAAAAAAAABAQ==" to "ETcAAAAAAAAFK8YjAgECDgE3AMAPAAAAAAAAAAABAQ=="
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi GPIO18: set On from false to true
[1/8/2020, 2:16:38 PM] [Rpi] raspberrypi History: set History Status from "ETcAAAAAAAAFK8YjAgECDgE3AMAPAAAAAAAAAAABAQ==" to "ETcAAAAAAAAFK8YjAgECDgE4AMAPAAAAAAAAAAABAQ=="
[1/8/2020, 2:16:51 PM] [Rpi] raspberrypi: set Current Temperature from 23.9°C to 21.8°C
[1/8/2020, 2:16:51 PM] [Rpi] raspberrypi: set Load from 0.26 to 0.27

Also, what does `set History Status` mean? They're very chatty in the log.

thank you / hartelijk dank

**Comment by ebaauw** [comment] 2020-01-08 21:35
> Afterwards, when I opened the window, I saw this in the logs:

What am I seeing here?  The GPIO input values bounces a couple of times (within the same second), but then remains stable?

> I am currently doing this with a custom built python script that polls the state of the GPIO pins every 60 seconds

homebridge-rpi only polls the RPi state: temperature, load, voltage, cpu frequency.  It sets up `pigpio` to issue notifications for changes to GPIO pins.  Typically, an input pin needs to time to stabilise when its value changes, causing multiple events to be fired (a couple of milliseconds apart, or event with the same millisecond).  You'll never get to see this with polling.

> Also, what does set `History Status` mean?

_History Status_ is a characteristic used by Eve to display history graphs.  Current version of homebridge-rpi assumes a [Pimoroni Fan Shim](https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-fan-shim).  The shim uses GPIO18 to turn on/off the fan.  Hence GPIO18 is exposed as a (stateful) _Switch_, with history when it was on.

The Fan Shim has a button connected to GPIO17, configured as input with a pull up.  I managed to expose it as a _Stateless Programmable Switch_, supporting _Short Press_ and _Long Press_.  I issue the HomeKit events on releasing the button (state changes from pressed to released), ignoring a release within 20 msec of pressing to cope with debouncing effects.

Of course, the window sensor is stateful, but I can probably use similar logic to ignore input pin changes too quickly after the previous one, before changing the window state.

**Comment by ebaauw** [comment] 2020-01-11 14:03
Could you guys have a look at v0.0.3 and let me know me what you think?

**Closed** 2020-01-17 15:52 UTC
